"""create_tag_model_and_association

Revision ID: 0188b8b1b368
Revises: 0d76f7ec2b26
Create Date: 2025-08-06 17:29:36.385764

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0188b8b1b368'
down_revision = '0d76f7ec2b26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('summary', sa.Text(), nullable=True))
    op.add_column('files', sa.Column('last_processed_at', sa.DateTime(), nullable=True))
    op.add_column('files', sa.Column('processing_status', sa.String(length=20), nullable=True))
    op.add_column('files', sa.Column('processing_model', sa.String(length=50), nullable=True))
    op.alter_column('files', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('files', 'path',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('files', 'size',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('files', 'type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('files', 'upload_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_index('idx_file_processing_status', 'files', ['processing_status'], unique=False)
    op.create_index('idx_file_type', 'files', ['type'], unique=False)
    op.create_index('idx_file_upload_date', 'files', ['upload_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_file_upload_date', table_name='files')
    op.drop_index('idx_file_type', table_name='files')
    op.drop_index('idx_file_processing_status', table_name='files')
    op.alter_column('files', 'upload_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('files', 'type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('files', 'size',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('files', 'path',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('files', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('files', 'processing_model')
    op.drop_column('files', 'processing_status')
    op.drop_column('files', 'last_processed_at')
    op.drop_column('files', 'summary')
    # ### end Alembic commands ###